docs/dcat-ap-no/01_Introduksjon.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/22_Kontrollerte_vokabular.adoc

Lukker #142, #144, #102, #101, #100 og #99

Oystein22 02

---

docs/dcat-ap-no/10_Datatjeneste.adoc

Lagt til underoverskrifter til #147

Oystein24 2

---

docs/dcat-ap-no/06_Oversikt_over_klasser.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/12_Distribusjon.adoc

Lukker #98, #97, #89, #88, og #87

Oystein24 3

---

docs/dcat-ap-no/01_Introduksjon.adoc
docs/dcat-ap-no/06_Oversikt_over_klasser.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/15_Kategori.adoc
docs/dcat-ap-no/16_Sjekksum.adoc
docs/dcat-ap-no/17_Identifikator.adoc
docs/dcat-ap-no/18_Lisensdokument.adoc

Oystein2502

---

docs/dcat-ap-no/08_Katalog.adoc

jim 20200325 kap08

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/15_Kategori.adoc
docs/dcat-ap-no/16_Sjekksum.adoc
docs/dcat-ap-no/18_Lisensdokument.adoc
docs/dcat-ap-no/19_Lokasjon.adoc
docs/dcat-ap-no/20_Tidsrom.adoc
docs/dcat-ap-no/21_Relasjoner.adoc
docs/dcat-ap-no/22_Kontrollerte_vokabular.adoc
ontology/dcatno-turtle.ttl

sett gjennom formattering fra Jim

Jim 20200325 kap22

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap10

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/11_Datasett.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap09

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap12

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap14

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap13

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/15_Kategori.adoc
docs/dcat-ap-no/16_Sjekksum.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap16

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/15_Kategori.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap15

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/15_Kategori.adoc
docs/dcat-ap-no/16_Sjekksum.adoc
docs/dcat-ap-no/18_Lisensdokument.adoc
docs/dcat-ap-no/19_Lokasjon.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap19

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/15_Kategori.adoc
docs/dcat-ap-no/16_Sjekksum.adoc
docs/dcat-ap-no/18_Lisensdokument.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap18

---

docs/dcat-ap-no/04b_Om_kravene.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/10_Datatjeneste.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/13_Aktor.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/15_Kategori.adoc
docs/dcat-ap-no/16_Sjekksum.adoc
docs/dcat-ap-no/18_Lisensdokument.adoc
docs/dcat-ap-no/19_Lokasjon.adoc
docs/dcat-ap-no/20_Tidsrom.adoc
docs/dcat-ap-no/21_Relasjoner.adoc
ontology/dcatno-turtle.ttl

Jim 20200325 kap21

---

docs/dcat-ap-no/08_Katalog.adoc

Revert "jim 20200325 kap08"

---

docs/dcat-ap-no/11_Datasett.adoc

For å løse #21 trengs bare å eksemplifisere. Har nå lagt inn eksempel.

Eksempel på tidsserier (#21)

---

docs/dcat-ap-no/06_Oversikt_over_klasser.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/17_Identifikator.adoc
docs/dcat-ap-no/20_Tidsrom.adoc

Jf. Excel-fil med avvik. Dette er første forsøk på å luke bort utilsiktede avvik.

Å luke bort utilsiktede avvik

---

docs/dcat-ap-no/17_Identifikator.adoc

Ny økt med å luke bort utilsiktede avvik

Ny økt med å luke bort utilsiktede avvik.

---

docs/dcat-ap-no/11_Datasett.adoc

Legger til eksempel på Opphav, #42.

Eksempler på opphav (#42)

---

docs/dcat-ap-no/06_Oversikt_over_klasser.adoc
docs/dcat-ap-no/17_Identifikator.adoc

Oppdaterer lenker til DCAT2, #196 (to gjenstår, fins ikke i DCAT2)

Jim lenker til dcat2

---

docs/dcat-ap-no/11_Datasett.adoc

Legger inn eksempler på type datasett, #37

Eksempel type datasett (#37)

---

docs/dcat-ap-no/01_Introduksjon.adoc
docs/dcat-ap-no/05_Ord_uttrykk_forkortelser.adoc
docs/dcat-ap-no/06_Oversikt_over_klasser.adoc
docs/dcat-ap-no/07_Oversikt_over_URIer.adoc
docs/dcat-ap-no/08_Katalog.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
docs/dcat-ap-no/14_Kategoriskjema.adoc
docs/dcat-ap-no/18_Lisensdokument.adoc
docs/dcat-ap-no/20_Tidsrom.adoc
docs/dcat-ap-no/22_Kontrollerte_vokabular.adoc

Fant en del typos (og dobbelt-space) som rettes opp.

Jim 20200407 typos

---

docs/dcat-ap-no/06_Oversikt_over_klasser.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/11_Datasett.adoc
docs/dcat-ap-no/12_Distribusjon.adoc

Fant en skrivefeil

---

docs/dcat-ap-no/06_Oversikt_over_klasser.adoc
docs/dcat-ap-no/09_Katalogpost.adoc
docs/dcat-ap-no/12_Distribusjon.adoc
ontology/dcatno-turtle.ttl

Tar unna noe opprydding i review-versjonen, for å få en så ren som mulig versjon før vi ev. går i gang med å aligne med BRegDCAT-AP.

Opprydding review før ev. BReg

---

docs/dcat-ap-no/22_Kontrollerte_vokabular.adoc
docs/dcat-ap-no/main.adoc

Mer opprydding før bruk av BRegDCAT

---

README.md
docs/04_Forvaltningsregime.adoc
docs/10_Egenskaper_for_klassen_Datasett.adoc
docs/introduksjon.adoc
docs/main.adoc

 Har erstattet "Difi" med "Digitaliseringsdirektoratet" ++

---

docs/01_Introduksjon.adoc
docs/02_Avvik.adoc
docs/03_Omfang_og_avgrensing.adoc
docs/04_Forvaltningsregime.adoc
docs/05_Ord_uttrykk_forkortelser.adoc
docs/main.adoc
docs/shared/download.adoc

Begynner med å rette mot BRegDCAT-AP, nå med justeringer i innledende kapitler.

Tilpasses BReg-DCAT-AP

---

docs/06_Oversikt_over_klasser.adoc
docs/07_Oversikt_over_URIer.adoc

Tilpasser Klasseoversikten (06...adoc) til BRegDCAT-AP (#218), alfabetisk sortering etter norske klassenavn.

Tilpasses BRegDCAT-AP-NO

---

docs/Klasse_Aktor.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Datastrukturdefinisjon.adoc
docs/Klasse_Datatjeneste.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Identifikator.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Katalogpost.adoc
docs/Klasse_Komponentspesifikasjon.adoc
docs/Klasse_Lisensdokument.adoc

En økt på å tilpasse egenskapene til BRegDCAT-AP. 
Dekker bl.a. følgende issues: #219, #220, #221, #222.

Tilpasser egenskapene til BRegDCAT-AP

---

docs/main.adoc

Så ikke at PDF-nedlasting manglet før nå.

Føye til mulighet for PDF-nedlasting i main.adoc

---

ontology/dcatno-turtle.ttl

Justert på diverse (definisjoner, merknader osv.) av predefinerte datasett-typer i dette vokabularet.

Oppdaterer ontologien dcatno.

---

docs/Klasse_Katalog.adoc

@ToHelland Det står nå 1..* i UML og må rettes.

Denne skulle vært anbefalt og 0..n

---

docs/Klasse_Datasett.adoc

Tar med denne oppdateringen også, når vi først oppdaterer. Endrer ikke kravene og trenger derfor ikke nevnes i endingsloggen.

Oppdaterer eksempel på datasett: type, Issue #279

---

docs/03_Omfang_og_avgrensing.adoc
docs/06_Oversikt_over_klasser.adoc
docs/07_Oversikt_over_URIer.adoc
docs/22_Kontrollerte_vokabular.adoc
docs/Klasse_Aktor.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Datastrukturdefinisjon.adoc
docs/Klasse_Datatjeneste.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Identifikator.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Katalogpost.adoc
docs/Klasse_Komponentspesifikasjon.adoc
docs/Klasse_Lisensdokument.adoc
docs/Klasse_Lokasjon.adoc
docs/Klasse_Offentlig_organisasjon.adoc
docs/Klasse_Offentlig_tjeneste.adoc
docs/Klasse_Regel.adoc
docs/Klasse_Regulativ_ressurs.adoc
docs/Klasse_Relasjoner.adoc
docs/Klasse_Sjekksum.adoc
docs/Klasse_Standard.adoc
docs/Klasse_Tema.adoc
docs/Klasse_Tematisk_skjema.adoc
docs/Klasse_Tidsrom.adoc
docs/Krav_om_å_bruke_kontrollerte_vokabularer.adoc
docs/main.adoc

Starter å justere DCAT-AP-NO. Dette er de første justeringene jeg har tatt, hvorav noen er "gjennomgående".

Jim-justering 1 etter høring

---

docs/06_Oversikt_over_klasser.adoc
docs/07_Oversikt_over_URIer.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Regel.adoc
docs/XX_endringslogg.adoc

Runde nr. 2 med justeringer etter høringen (dekker flere issues).

Jim justering2 etter høring

---

docs/22_Kontrollerte_vokabular.adoc

Usikker på om dette er riktig måte å gjøre det på. Tenkte at det kanskje ikke strakk til å kun skrive det ut en gang gitt at dokumentet leses stykkevis antakelig. Dette er det "vanskeligste" akronymet tror jeg. Dessuten står NAL alltid sammen med noe foran, så å sette (NAL) i parantes etter å ha skrevet det ut kan være forvirrende.

NAL -> Named Authority List

---

docs/06_Oversikt_over_klasser.adoc
docs/07_Oversikt_over_URIer.adoc
docs/22_Kontrollerte_vokabular.adoc
docs/Klasse_Aktor.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Datatjeneste.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Katalogpost.adoc
docs/Klasse_Tema.adoc

Diverse redaksjonelle endringer

Red endringer

---

docs/06_Oversikt_over_klasser.adoc
docs/22_Kontrollerte_vokabular.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Datatjeneste.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Katalogpost.adoc
docs/Klasse_Tema.adoc

parallelle språkv -> ulike språk/målformer

Sprakversjoner

---

docs/06_Oversikt_over_klasser.adoc
docs/22_Kontrollerte_vokabular.adoc
docs/Klasse_Datasett.adoc

Lagt inn lenker i tekst til enkelte fotnoter. Endel fotnoter krever at vi skriver mer tekst. Det har jeg ikke gjort. Ref rad 40 i excel-arket.

Lagt inn lenker i tekst til enkelte fotnoter

---

docs/22_Kontrollerte_vokabular.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Distribusjon.adoc

Jim justering5 etter høring

---

docs/Klasse_Datasett.adoc
docs/Klasse_Datatjeneste.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Katalogpost.adoc

Diverse redaksjonelle endringer

Div redaksjonelle endringer

---

docs/Klasse_Datatjeneste.adoc
docs/Klasse_Katalogpost.adoc
docs/Klasse_Offentlig_tjeneste.adoc

Ferdig til og med kommentarer fra SSB

Red endringer3

---

docs/06_Oversikt_over_klasser.adoc
docs/Klasse_Aktor.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Datatjeneste.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Dokument.adoc
docs/Klasse_Identifikator.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Katalogpost.adoc
docs/Klasse_Lisensdokument.adoc
docs/Klasse_Lokasjon.adoc
docs/Klasse_Offentlig_organisasjon.adoc
docs/Klasse_Offentlig_tjeneste.adoc
docs/Klasse_Regel.adoc
docs/Klasse_Regulativ_ressurs.adoc
docs/Klasse_Relasjoner.adoc
docs/Klasse_Sjekksum.adoc
docs/Klasse_Standard.adoc
docs/Klasse_Tema.adoc
docs/Klasse_Tematisk_skjema.adoc
docs/Klasse_Tidsrom.adoc
docs/main.adoc

Jim justering6 etter høring

---

docs/02_Avvik.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Dokument.adoc
docs/XX_endringslogg.adoc

Dekker 2 issues + et par feilrettinger.

Jim justering7 etter høring

---

docs/06_Oversikt_over_klasser.adoc

En endring

---

docs/01_Introduksjon.adoc
docs/03_Omfang_og_avgrensing.adoc
docs/04_Forvaltningsregime.adoc
docs/04b_Om_kravene.adoc
docs/05_Ord_uttrykk_forkortelser.adoc
docs/06_Oversikt_over_klasser.adoc
docs/07_Oversikt_over_URIer.adoc
docs/07b_diagram.adoc
docs/22_Kontrollerte_vokabular.adoc
docs/Klasse_Distribusjon.adoc
docs/Klasse_Dokument.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Katalogpost.adoc
docs/Klasse_Tematisk_skjema.adoc
docs/Krav_om_å_bruke_kontrollerte_vokabularer.adoc

Kommentar føyes til abstrakt klasse dcat:Resource

---

docs/03_Omfang_og_avgrensing.adoc
docs/06_Oversikt_over_klasser.adoc
docs/22_Kontrollerte_vokabular.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Katalog.adoc
docs/Klasse_Offentlig_organisasjon.adoc

Diverse redaksjonelle endringer

Diverse redaksjonelle endringer

---

docs/06_Oversikt_over_klasser.adoc
docs/Klasse_Datasett.adoc
docs/Klasse_Distribusjon.adoc

Rettinger ref NAVs kommentarer

---

docs/main.adoc

til a&s-rådet + publiseringsdato i main-fil

Status og publisertdato i main

---

docs/XX_endringslogg.adoc

endringslogg tidsromsoppløsning

---

docs/XX_endringslogg.adoc

Redaksjonelle oppdateringer, kun i endringsloggen

Redaksjonelle oppdateringer i endringsloggen
